---
title: "Central Euorope COVID19"
author: "Compiled by Dr. Ryan Johnson using data from @COVID19."
date: "Last updated `r format(Sys.time(), '%A, %B %d, %Y')`"
output:
  html_document:
    df_print: paged
bibliography: bibliography.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

library(COVID19)
library(tidyverse)
library(zoo)
```

```{r, results='hide'}
C <- covid19() %>%
  mutate(date = as.Date(date),
         difdeaths = prepend(diff(deaths), 0),
         difconfirmed = prepend(diff(confirmed), 0),
         hosp_per = hosp / population * 100000,
         deaths_per = difdeaths / population * 100000,
         cases_per = difconfirmed / population * 100000,
         vac_per = people_vaccinated / population) %>%
  rename(country = administrative_area_level_1) %>%
  filter(country %in% c("Austria", "Hungary", "United States"),
         date >= as.Date("2021-03-01"))
```

```{r}
C %>%
  ggplot(aes(x = date, y = hosp_per, color = country)) +
  geom_line(size = 1) + 
  labs(y = "Hospitalizations per 100,000",
       title = "Hospitalizations")
```
```{r}
C %>%
  ggplot(aes(x = date, y = cases_per, color = country)) +
  geom_smooth(span = 0.1, se = FALSE) + 
  geom_point() +
  labs(y = "Confirmed Cases per 100,000",
       title = "Confirmed Cases")
```
```{r}
C %>%
  ggplot(aes(x = date, y = deaths_per, color = country)) +
  geom_smooth(span = 0.1, se = FALSE) + 
  geom_point() +
  labs(y = "Confirmed Deaths per 100,000",
       title = "Confirmed Deaths")
```

```{r}
```{r}
C %>%
  ggplot(aes(x = date, y = vac_per, color = country)) +
  geom_line(size = 1) + 
  scale_y_continuous(labels = scales::percent) +
  labs(y = "Vaccinated",
       title = "Vacinated")
```
```

