---
title: "COVID19 Data Near Kosciusko County"
author: "Compiled by Dr. Ryan Johnson using data from @NYT based on reports from state and local health agencies by way of @COVID19."
date: "Last updated `r format(Sys.time(), '%A, %B %d, %Y')`"
output:
  html_document:
    df_print: paged
bibliography: bibliography.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

library(ggiraph)
library(patchwork)
library(COVID19)
library(albersusa)
library(tidygeocoder)
library(ggmap)
library(tidyverse)

```

## R Markdown

```{r}
data_url <- "https://github.com/owid/covid-19-data/raw/master/public/data/vaccinations/us_state_vaccinations.csv"

all_data <- read.csv(data_url)
all_data$location[all_data$location == "New York State"] <- "New York"

not_states_or_dc <- c("American Samoa", "Bureau of Prisons", 
  "Dept of Defense", "Federated States of Micronesia", "Guam", 
  "Indian Health Svc", "Long Term Care", "Marshall Islands", 
  "Northern Mariana Islands", "Puerto Rico", "Republic of Palau", 
  "United States", "Veterans Health", "Virgin Islands")

max_date <- all_data %>%
  pull(date) %>%
  max()
bar_graph_data_recent <- all_data %>%  
  filter(date == max_date, !(location %in% not_states_or_dc)) %>%
  rename(State = location) %>%
  mutate(
   PctFullyVaccinated = round(people_fully_vaccinated_per_hundred, 1),
   tooltip_text = paste0(toupper(State), "\n", 
                   PctFullyVaccinated, "%")
  ) %>%  
  select(State, PctFullyVaccinated, tooltip_text)
```


```{r}
latest_vax_graph <- ggplot(bar_graph_data_recent, 
                aes(x = reorder(State, PctFullyVaccinated), 
                    y = PctFullyVaccinated,
                    tooltip = tooltip_text, data_id = State #<<
                    )) +
  geom_col_interactive(color = "black", fill="#0072B2", size = 0.5) +  #<<
  theme_minimal() +
  theme(axis.text=element_text(size = 6)) +  #<<
  labs(title = str_glue("Percent Fully Vaccinated ", format.Date(max_date, "%B %d, %Y")),
       subtitle = "Data from Our World in Data GitHub repo"
       ) +
   ylab("") +
   xlab("") +
  coord_flip() +
  scale_y_continuous(limits = c(0,100))

#girafe(ggobj = latest_vax_graph, width_svg = 5, height_svg = 4)
```

```{r}

us_sf <- usa_sf("lcc") %>%
  mutate(State = as.character(name))

state_map <- ggplot() +
  geom_sf_interactive(data = us_sf, size = 0.125, 
                      aes(data_id = State, tooltip = State)) +
  theme_void()
```

```{r}
girafe(ggobj = state_map + latest_vax_graph, 
       width_svg = 10, height_svg = 5) %>%
  girafe_options(opts_hover(css = "fill:cyan;"))
```


```{r}
per = 8*10^4 #dislplay rates per how many people?
per_word = "Eighty Thousand"
data_start = as.Date("2020-03-20") #Start data at this day
states <- c("Michigan", "Illinois", "Ohio", "Kentucky")
KOS_neighbor_counties <- c("Fulton", "Marshall", "Elkhart", "Noble", "Whitley", "Allen", "Wabash")
#What is the latest date of the data?
yest <- Sys.Date() - 1 #Weird stuff going on with updating of data
#Get data and subset to states we want
US_states <- covid19("US", level = 2, start = data_start, end = yest) %>%
  #Compute per-day numbers from totals
  mutate(difdeaths = prepend(diff(deaths), 0),
         difconfirmed = prepend(diff(confirmed), 0),
         diftests = prepend(diff(tests), 0)) %>%
  #Compute per-population numbers
  mutate(confirmedper = confirmed / population * per,
         deathsper = deaths / population * per,
         testsper = tests / population * per,
         difconfirmed_per = difconfirmed / population * per,
         difdeaths_per = difdeaths / population * per,
         diftests_per = diftests / population * per,
         hosp_per = hosp / population * per)

#Some convenient date subsets
covyest <- US_states[US_states$date == yest,]
covlabel <- US_states[US_states$date == as.Date("2020-04-20"),]
cov5 <- US_states[US_states$date <= yest & US_states$date > (yest - 5),]
cov14 <- US_states[US_states$date <= yest & US_states$date > (yest - 14),]
#State-level subsets
Indiana <- subset(US_states, administrative_area_level_2 == "Indiana")
IN_neighbors <- subset(US_states, administrative_area_level_2 %in% states)
#County Level Data
url = "https://hub.mph.in.gov/dataset/bd08cdd3-9ab1-4d70-b933-41f9ef7b809d/resource/afaa225d-ac4e-4e80-9190-f6800c366b58/download/covid_report_county_date.xlsx"
httr::GET(url, httr::write_disk(tf <- tempfile(fileext = ".xlsx")))
IN_counties <- readxl::read_excel(tf)%>%
  #Correct data structures
  mutate(DATE = as.Date(DATE),
         COUNTY_NAME = factor(COUNTY_NAME))%>%
  #Filter after data_start
  filter(DATE > data_start) %>%
  #Compute per-day numbers
  mutate(difdeaths = COVID_DEATHS,
         difconfirmed = COVID_COUNT)
#Hospital Data
url = "https://hub.mph.in.gov/dataset/4d31808a-85da-4a48-9a76-a273e0beadb3/resource/0c00f7b6-05b0-4ebe-8722-ccf33e1a314f/download/covid_report_bedvent_date.xlsx"
httr::GET(url, httr::write_disk(tf <- tempfile(fileext = ".xlsx")))
IN_hosp <- readxl::read_excel(tf) %>%
  mutate(DATE = as.Date(DATE))%>%
  filter(DATE > as.Date("2020-04-07"))%>%
  rename(covid = PCT_BEDS_ICU_OCCUPIED_COVID_19,
         non_covid = PCT_BEDS_ICU_NO_OCCUPIED_COVID_19,
         available = PCT_BEDS_AVAILABLE_ICU_BEDS_TOTAL) %>%
  select(DATE, covid:available)%>%
  pivot_longer(cols = covid:available,
               names_to = "percent") %>%
  mutate(percent = factor(percent,levels = c("covid",
                                             "non_covid",
                                             "available")))
#More Hospital Data
#round_date(yest, unit = "week", week_start = 7)
#yest_str = format(floor_date(yest, unit = "week", week_start = 7), format = "%Y%m%d")
#url = str_glue("https://healthdata.gov/sites/default/files/reported_hospital_capacity_admissions_facility_level_weekly_average_timeseries_","{yest_str}", ".csv")
url = "https://healthdata.gov/api/views/anag-cw7u/rows.csv?accessType=DOWNLOAD"
US_indiv_hosp <- read.csv(url) %>%
  select(c(2:10, 22, 24, 26)) %>%
  rename(total = total_icu_beds_7_day_avg,
         used = icu_beds_used_7_day_avg,
         covid = staffed_icu_adult_patients_confirmed_and_suspected_covid_7_day_avg,
         fips = fips_code) %>%
  mutate(covid = replace(covid, which(covid < 0L), 2), #Choosing 2 is arbitrary, but I don't think it will matter
         used = replace(used, which(used < 0L), NA),    
         total = replace(total, which(total < 0L), NA), 
         fips = case_when(
           str_length(fips) == 4 ~ str_pad(fips, width = 5, side = "left", pad = 0),
           TRUE ~ as.character(fips))) %>%
  filter(!is.na(used),
         !is.na(total),
         address != '',
         ccn != '',
         collection_week == max(collection_week)) %>%
  mutate(used_pct = used/total,
         cov_pct = covid/total) %>%
  filter(used_pct > 0.9)
#Commented out because it takes too long.  Join with 
#US_indiv_hosp2 <- US_indiv_hosp %>%
#  filter(!is.na(used),
#         !is.na(total),
#         address != '',
#         ccn != '') %>%
#  geocode(street = address,
#          city = city,
#          postalcode = zip,
#          state = state) %>%
#  filter(!is.na(lat))
#View(US_indiv_hosp2)
#save(US_indiv_hosp2, file = "data/hosps_coords.Rdata")
load("data/hosps_coords.Rdata")
#Find any hospitals from US_indiv_hosp that don't have lat-long data, and add it with Google geocode
US_indiv_hosp2 <- US_indiv_hosp %>%
  anti_join(US_indiv_hosp2, by = "ccn") %>%
  add_row(address = "", city = "", state = "", zip = 0) %>%
  mutate(location = str_glue("{address}, {city}, {state}, {zip}")) %>%
  mutate_geocode(location) %>%
  rename(long = lon) %>%
  select(collection_week:covid, lat, long) %>%
  rbind(US_indiv_hosp2) %>%
  filter(!is.na(ccn))
save(US_indiv_hosp2, file = "hosps_coords.R") #Save for next time
US_indiv_hosp3 <- US_indiv_hosp2 %>%
  select(ccn, lat, long) %>%
  right_join(US_indiv_hosp, by = "ccn")%>%
  relocate(long, lat) %>%
  drop_na() %>%
  usmap_transform() %>%
  mutate(used_pct = ifelse(used_pct > 1, 1, used_pct),
         cov_pct = ifelse(cov_pct > 1, 1, cov_pct))
IN_county_hosp <- US_indiv_hosp %>%
  group_by(state, fips) %>%
  summarise(total = sum(total, na.rm = TRUE),
            used = sum(used, na.rm = TRUE),
            covid = sum(covid, na.rm = TRUE)) %>%
  mutate(cov_pct = covid/total,
         non_pct = (used-covid)/total)
#Add geographic and population data
lat_and_long <- read_excel("lat_and_long.xlsx") %>%
  mutate(COUNTY_NUMERIC = COUNTY_NUMERIC + 18000)
load("county_populations.RData")
IN_counties <- pops %>%
  full_join(y = lat_and_long,
            by = c("key_numeric"="COUNTY_NUMERIC"))%>%
  mutate(key_numeric = as.character(key_numeric))%>%
  full_join(y = IN_counties,
            by = c("key_numeric" = "LOCATION_ID")) %>%
  #Compute per-population numbers
  mutate(confirmedper = COVID_COUNT / population * per,
         deathsper = COVID_DEATHS / population * per,
         difconfirmed_per = difconfirmed / population * per,
         difdeaths_per = difdeaths / population * per,
         county = COUNTY_NAME.x) %>%
  left_join(y = IN_county_hosp,
            by = c("key_numeric" = "fips"))
Indices <- IN_counties %>%
  group_by(COUNTY_NAME.x) %>%
  mutate(POSITIVE_TEST_RATE_MOVING_AVG = lag(POSITIVE_TEST_RATE_MOVING_AVG, 6),
         ALL_TESTS_POSITIVE_TEST_RATE_MOVING_AVG =
           lag(ALL_TESTS_POSITIVE_TEST_RATE_MOVING_AVG, 6)) %>%
  filter(DATE == yest-1) %>%
  ungroup() %>%
  mutate(Case_per = COVID_COUNT_MOVING_AVG / population * per,
         case_index = Case_per/sum(Case_per),
         positivity_index = POSITIVE_TEST_RATE_MOVING_AVG/sum(POSITIVE_TEST_RATE_MOVING_AVG),
         combined = sqrt(case_index * positivity_index),
         dashboard = Case_per/2 + POSITIVE_TEST_RATE_MOVING_AVG/10,
         fips = key_numeric)
 
Indices <- Indices[order(-Indices$combined),]
outbreaks <- Indices$COUNTY_NAME.x[1:6] 
Kos <- subset(IN_counties, county == "Kosciusko", DATE < yest)
IN_outbreak <- subset(IN_counties, county %in% outbreaks)
KOS_neighbors <- subset(IN_counties, county %in% KOS_neighbor_counties)
gg_color_hue <- function(n) {
  hues = seq(15, 375, length = n + 1)
  hcl(h = hues, l = 65, c = 100)[1:n]
}
weekspan <- 3*7/(as.numeric(yest) - as.numeric(data_start)+2)
```

```{r}
US_states %>%
  filter(date == max_date) %>%
  inner_join(y = bar_graph_data_recent, by = c("administrative_area_level_2" = "State")) %>%
  ggplot(aes(x = PctFullyVaccinated, y = hosp/population*10000)) +
  geom_text(aes(label = key_alpha_2)) +
  labs(title = "Current Hospitalization by Vaccine Rate") +
  ylab("Currently Hospitalized per Ten Thousand")
```

